redesign
js-accounts/react pull request #44
Opened 2017-05-18 09:11 UTC by pradel

2017-05-24 20:36 UTC, davidyaha reviewed
So I  really like the fact that this new implementation is much much more compact :)
One issue I have in general is that we've tried to push the state back to the accounts package but instead we moved it to the components.. It seems like we should figure out a way to get rid of the stateful components altogether... not sure if there is a good way but maybe if we expose the store from the accounts client, and just use the react-redux `Provider` as the returned value from `AccountsProvider` we can use `connect` for the signUp and logIn forms. 
Also we are missing the reset password still right?

2017-05-24 20:36 UTC, davidyaha commented on packages/material-ui/src/layout.js
> +  <Paper style={{ margin: 'auto', maxWidth: 400, marginTop: 50, padding: 20 }}>
So this is the default layout right? but then, I don't see any way of overriding it in a comfortable way

2017-05-24 20:36 UTC, davidyaha commented on packages/material-ui/src/log-in-form.js
> +    const errors = validate.logIn(accountsClient, form);
I think that loginWithPassword already handles validation isn't it?

2017-05-24 20:36 UTC, davidyaha commented on packages/material-ui/src/log-in-form.js
> +      accountsClient.changeRoute(accountsClient.options.homePath);
The route thing should really be part of the base react package I think..

2017-05-24 20:36 UTC, davidyaha commented on packages/react/src/with-current-user.js
> +    this.unsubscribe = this.context.accountsClient.store.subscribe(() => {
There is no way to make the subscribe callback more specific? like only try to set state if an action with user or loading was dispatched?
I think that this way we will cause a re-render for each component that uses that for every action..

2017-05-26 01:20 UTC, TimMikeladze requested changes

2017-05-26 01:20 UTC, TimMikeladze commented on packages/material-ui/src/log-in-form.js
> +    const errors = validate.logIn(accountsClient, form);
Yes it should handle validation. All validation should be handled by `@accounts/client`

2017-05-26 01:20 UTC, TimMikeladze commented on packages/material-ui/src/sign-up-form.js
> +      <Layout>
This logic can be moved to the core react package.

2017-05-26 01:28 UTC, TimMikeladze commented
Thanks for the PR @pradel 

I've been thinking about the redesign of both this package and the core accounts package. Before beginning any redesigns I think we should get our typing and building straightened out. See https://github.com/js-accounts/accounts/issues/44 for discussion about moving to TS. 

Also, I think the react packages can be written in such a way that they never depend on `@accounts/client` but instead are passed in functions as props (which probably come from `@accounts/client`).

2017-05-26 13:42 UTC, davidyaha commented
> Also, I think the react packages can be written in such a way that they never depend on @accounts/client but instead are passed in functions as props (which probably come from @accounts/client).

It is great for modularity but It will (probably, or at least the way I think of possible implementation) also complicate the usage by a lot.
One possible way to approach it will be with using object spreading

```
<LogInForm {...accountClient} />
```

This will probably render the provider useless..

2017-05-31 15:29 UTC, pradel commented on packages/material-ui/src/layout.js
> +  <Paper style={{ margin: 'auto', maxWidth: 400, marginTop: 50, padding: 20 }}>
- We can add a LayoutStyle prop
- We can add a Layout prop that can overwrite the package Layout with a user Component

2017-05-31 15:29 UTC, pradel commented on packages/material-ui/src/log-in-form.js
> +    const errors = validate.logIn(accountsClient, form);
Okay will take a look

2017-05-31 15:29 UTC, pradel commented on packages/react/src/with-current-user.js
> +    this.unsubscribe = this.context.accountsClient.store.subscribe(() => {
You are right I really don't know I will take a look at that

2017-05-31 15:30 UTC, pradel commented on packages/react/src/with-current-user.js
> +    this.unsubscribe = this.context.accountsClient.store.subscribe(() => {
Or if we use react-redux this can be done easily

2017-05-31 15:32 UTC, pradel commented on packages/material-ui/src/sign-up-form.js
> +      <Layout>
?

2018-03-28 09:01 UTC, closed without merging